export const AI_OPERATIONAL_AUDIT_DISPLAY = {
  headlineLead: "AI Operational Audits &",
  headlineAccent: "Cloud Diagnostics",
  tagline: "Find bottlenecks. Unlock automation. Build with confidence.",
  diagnoseLead: "We dig into your operations, data flows, and tools to find what's holding you back.",
  processLead: "A focused engagement. Real outcomes.",
  governanceNote: "Responsible AI. Real Business Impact.",
  formKicker: "Let's get started",
  formLead: "Tell us a bit about your needs and we'll tailor the right audit plan for you.",
  formAside: "Smarter Operations Ahead",
  ctaArrow: "→",
  chips: [
    { id: "discover", label: "Discover Hidden Bottlenecks" },
    { id: "prioritize", label: "Prioritize Automation" },
    { id: "govern", label: "Build with Governance" },
  ] as const,
  floats: [
    { id: "spreadsheets", title: "Spreadsheets" },
    { id: "manual", title: "Manual Processes" },
    { id: "legacy", title: "Legacy Systems" },
    { id: "cloud", title: "Cloud Infrastructure" },
    { id: "insight", title: "From inefficiency to intelligence" },
    { id: "note", title: "Audit today. Automate tomorrow." },
  ] as const,
  processNotes: {
    "days-1-3": "Deep-dive into your workflows, tools, and data sources.",
    "days-4-8": "Working automation prototype for your highest-value use case.",
    "days-9-14": "Complete architecture, tool stack, and implementation roadmap.",
  } as const,
  formChecks: ["Analyze", "Identify", "Automate", "Scale"] as const,
} as const;
