import { PRECISION_MINIMALIST_DESIGN } from "./precisionMinimalistDesign";

/** Stitch Proven Precision case studies canvas and card surfaces. */
export const CASE_STUDIES_CANVAS_BACKGROUND =
  PRECISION_MINIMALIST_DESIGN.colors.surfaceContainerLow;
export const CASE_STUDY_CARD_SURFACE = PRECISION_MINIMALIST_DESIGN.colors.background;
export const CASE_STUDY_CARD_BORDER_VAR = "var(--border-outline-variant)" as const;
export const CASE_STUDY_CARD_BORDER_COLOR = PRECISION_MINIMALIST_DESIGN.colors.borderOutlineVariant;
export const CASE_STUDY_CARD_RADIUS = "8px" as const;
export const CASE_STUDY_SHOWCASE_MEDIA_SURFACE = "#ffffff" as const;
export const CASE_STUDY_CARD_INNER_PADDING = "clamp(24px, 3vw, 32px)" as const;
export const CASE_STUDY_STACKED_IMAGE_MAX_HEIGHT = "200px" as const;
export const CASE_STUDY_COMMITERS_EDGE_INSET = CASE_STUDY_CARD_INNER_PADDING;
export const CASE_STUDY_COMMITERS_GUTTER = CASE_STUDY_COMMITERS_EDGE_INSET;
export const CASE_STUDY_COMMITERS_COPY_PADDING = CASE_STUDY_COMMITERS_EDGE_INSET;
export const CASE_STUDY_COMMITERS_COPY_PADDING_INLINE_END = "0" as const;
export const CASE_STUDY_COMMITERS_COPY_PADDING_BLOCK_END = "0" as const;
export const CASE_STUDY_COMMITERS_IMAGE_INSET = CASE_STUDY_COMMITERS_EDGE_INSET;
export const CASE_STUDY_COMMITERS_MEDIA_PADDING = CASE_STUDY_COMMITERS_IMAGE_INSET;
export const CASE_STUDY_COMMITERS_COLUMN_GAP = CASE_STUDY_COMMITERS_GUTTER;
export const CASE_STUDY_COMMITERS_CTA_PADDING_INLINE_START = CASE_STUDY_COMMITERS_EDGE_INSET;
export const CASE_STUDY_COMMITERS_CTA_PADDING_BLOCK_END = CASE_STUDY_COMMITERS_EDGE_INSET;
export const CASE_STUDY_COMMITERS_MEDIA_PADDING_BLOCK_END = CASE_STUDY_COMMITERS_IMAGE_INSET;
export const CASE_STUDY_COMMITERS_CARD_GRID_ROWS = "auto" as const;
export const CASE_STUDY_PROBLEM_SOLUTION_GAP = "1lh" as const;
export const CASE_STUDY_PROBLEM_SOLUTION_FLEX = "0 0 auto" as const;
export const CASE_STUDY_PROBLEM_SOLUTION_ALIGN_CONTENT = "start" as const;
export const CASE_STUDY_COMMITERS_PROBLEM_SOLUTION_GAP = CASE_STUDY_PROBLEM_SOLUTION_GAP;
export const CASE_STUDY_COMMITERS_PROBLEM_SOLUTION_FLEX = CASE_STUDY_PROBLEM_SOLUTION_FLEX;
export const CASE_STUDY_COMMITERS_COPY_GAP = "12px" as const;
/** @deprecated Use CASE_STUDY_COMMITERS_COPY_GAP */
export const CASE_STUDY_COMMITERS_COPY_GRID_GAP = CASE_STUDY_COMMITERS_COPY_GAP;
export const CASE_STUDY_COMMITERS_MEDIA_PADDING_BLOCK = CASE_STUDY_COMMITERS_MEDIA_PADDING;
export const CASE_STUDY_COMMITERS_MEDIA_PADDING_INLINE_START = "0" as const;
export const CASE_STUDY_COMMITERS_MEDIA_PADDING_INLINE_END = CASE_STUDY_COMMITERS_IMAGE_INSET;
export const CASE_STUDY_COMMITERS_IMAGE_BORDER_RADIUS = "0" as const;
export const CASE_STUDY_COMMITERS_MEDIA_PADDING_INLINE = CASE_STUDY_COMMITERS_MEDIA_PADDING_INLINE_END;
export const CASE_STUDY_AI_INNER_PADDING = CASE_STUDY_CARD_INNER_PADDING;
export const CASE_STUDY_AI_COPY_GAP = "12px" as const;
export const CASE_STUDY_AI_MEDIA_PADDING_BLOCK_START = CASE_STUDY_CARD_INNER_PADDING;
export const CASE_STUDY_AI_MEDIA_PADDING_INLINE = CASE_STUDY_CARD_INNER_PADDING;
export const CASE_STUDY_AI_MEDIA_PADDING_BLOCK_END = "0" as const;
/** @deprecated Use CASE_STUDY_AI_MEDIA_PADDING_BLOCK_START and related tokens */
export const CASE_STUDY_AI_MEDIA_PADDING = CASE_STUDY_AI_MEDIA_PADDING_BLOCK_START;
export const CASE_STUDY_AI_IMAGE_HEIGHT = "180px" as const;
export const CASE_STUDY_AI_IMAGE_MAX_HEIGHT = CASE_STUDY_AI_IMAGE_HEIGHT;
export const CASE_STUDY_AI_IMAGE_ASPECT_RATIO = "auto" as const;
export const CASE_STUDY_AI_IMAGE_BORDER_RADIUS = "4px" as const;
export const CASE_STUDY_AI_MEDIA_OVERFLOW = "hidden" as const;
export const CASE_STUDY_CARD_SQUARE_IMAGE_ASPECT_RATIO = "1 / 1" as const;
export const CASE_STUDY_NEARDROP_IMAGE_ASPECT_RATIO = CASE_STUDY_CARD_SQUARE_IMAGE_ASPECT_RATIO;
export const CASE_STUDY_NEARDROP_IMAGE_BORDER_RADIUS = CASE_STUDY_COMMITERS_IMAGE_BORDER_RADIUS;
export const CASE_STUDY_NEARDROP_MEDIA_OVERFLOW = "hidden" as const;
export const CASE_STUDY_NEARDROP_PROBLEM_SOLUTION_FLEX = "1" as const;
