/** Canonical CTA button tokens — compact Stitch geometry with role-based colors. */
export const SITE_BUTTON_DESIGN = {
  radius: "8px",
  minHeight: "40px",
  paddingInline: "18px",
  paddingBlock: "10px",
  fontSize: "0.9rem",
  fontWeight: 600,
  actionsGap: "10px",
  colors: {
    primaryBackground: "var(--stitch-blue)",
    primaryBorder: "var(--stitch-blue)",
    primaryText: "#ffffff",
    primaryHoverBackground: "var(--stitch-blue-hover)",
    secondaryBackground: "var(--surface)",
    secondaryBorder: "var(--border)",
    secondaryText: "var(--text)",
    secondaryHoverBackground: "var(--surface-soft)",
  },
  bandCta: {
    primaryBackground: "#0066ff",
    primaryBorder: "#0066ff",
    primaryText: "#ffffff",
    primaryHoverBackground: "#0052cc",
    secondaryBackground: "#ffffff",
    secondaryBorder: "#e5e7eb",
    secondaryText: "#111827",
    secondaryHoverBackground: "#f8f9fa",
  },
} as const;

export const SITE_BUTTON_CSS_VARIABLES = {
  "--site-btn-radius": SITE_BUTTON_DESIGN.radius,
  "--site-btn-min-height": SITE_BUTTON_DESIGN.minHeight,
  "--site-btn-padding-x": SITE_BUTTON_DESIGN.paddingInline,
  "--site-btn-padding-y": SITE_BUTTON_DESIGN.paddingBlock,
  "--site-btn-font-size": SITE_BUTTON_DESIGN.fontSize,
  "--site-btn-font-weight": String(SITE_BUTTON_DESIGN.fontWeight),
  "--site-btn-primary-bg": SITE_BUTTON_DESIGN.colors.primaryBackground,
  "--site-btn-primary-border": SITE_BUTTON_DESIGN.colors.primaryBorder,
  "--site-btn-primary-text": SITE_BUTTON_DESIGN.colors.primaryText,
  "--site-btn-primary-hover-bg": SITE_BUTTON_DESIGN.colors.primaryHoverBackground,
  "--site-btn-secondary-bg": SITE_BUTTON_DESIGN.colors.secondaryBackground,
  "--site-btn-secondary-border": SITE_BUTTON_DESIGN.colors.secondaryBorder,
  "--site-btn-secondary-text": SITE_BUTTON_DESIGN.colors.secondaryText,
  "--site-btn-secondary-hover-bg": SITE_BUTTON_DESIGN.colors.secondaryHoverBackground,
  "--site-btn-band-primary-bg": SITE_BUTTON_DESIGN.bandCta.primaryBackground,
  "--site-btn-band-primary-border": SITE_BUTTON_DESIGN.bandCta.primaryBorder,
  "--site-btn-band-primary-text": SITE_BUTTON_DESIGN.bandCta.primaryText,
  "--site-btn-band-primary-hover-bg": SITE_BUTTON_DESIGN.bandCta.primaryHoverBackground,
  "--site-btn-band-secondary-bg": SITE_BUTTON_DESIGN.bandCta.secondaryBackground,
  "--site-btn-band-secondary-border": SITE_BUTTON_DESIGN.bandCta.secondaryBorder,
  "--site-btn-band-secondary-text": SITE_BUTTON_DESIGN.bandCta.secondaryText,
  "--site-btn-band-secondary-hover-bg": SITE_BUTTON_DESIGN.bandCta.secondaryHoverBackground,
} as const;
