import { PRECISION_MINIMALIST_DESIGN } from "./precisionMinimalistDesign";
import { STITCH_LIGHT_PALETTE } from "./stitchLightPalette";

const { colors, typography, spacing, radius } = PRECISION_MINIMALIST_DESIGN;

/** Theme tokens — Precision Minimalist void-first palette mapped to CSS variables. */
export const LOGO_THEME = {
  brandGold: STITCH_LIGHT_PALETTE.kickerTan,
  brandGoldDeep: "#7a6240",
  brandGoldSoft: "#e8dfd2",
  darkNavy: colors.heading,
  teal: colors.primary,
  tealDeep: colors.primaryHover,
  cream: colors.background,
  slate: colors.muted,
  white: colors.background,
  ink: colors.heading,
  deepFooter: colors.surfaceContainerLow,
  pageBackground: colors.background,
  surface: colors.background,
  surfaceSoft: colors.surfaceContainerLow,
  muted: colors.body,
  text: colors.heading,
  bodyText: colors.body,
  primaryRgb: colors.primaryRgb,
  tealRgb: colors.primaryRgb,
  navyRgb: "17, 24, 39",
  whiteRgb: "255, 255, 255",
  circuitOpacity: 0.06,
  stitchBlue: colors.primary,
  stitchBlueHover: colors.primaryHover,
} as const;

export type LogoThemeKey = keyof typeof LOGO_THEME;

export const LOGO_CSS_VARIABLES = {
  "--brand-gold": LOGO_THEME.brandGold,
  "--brand-gold-deep": LOGO_THEME.brandGoldDeep,
  "--brand-gold-soft": LOGO_THEME.brandGoldSoft,
  "--dark-navy": LOGO_THEME.darkNavy,
  "--teal": LOGO_THEME.stitchBlue,
  "--teal-deep": LOGO_THEME.stitchBlueHover,
  "--cream": LOGO_THEME.cream,
  "--slate": LOGO_THEME.slate,
  "--footer-deep": LOGO_THEME.deepFooter,
  "--text": LOGO_THEME.text,
  "--muted": LOGO_THEME.muted,
  "--body-text": LOGO_THEME.bodyText,
  "--silver-muted": LOGO_THEME.slate,
  "--white": LOGO_THEME.white,
  "--bg": LOGO_THEME.surface,
  "--page-background": LOGO_THEME.pageBackground,
  "--surface": LOGO_THEME.surface,
  "--surface-soft": LOGO_THEME.surfaceSoft,
  "--surface-container-low": colors.surfaceContainerLow,
  "--stitch-blue": LOGO_THEME.stitchBlue,
  "--stitch-blue-hover": LOGO_THEME.stitchBlueHover,
  "--stitch-blue-rgb": LOGO_THEME.primaryRgb,
  "--gold-bright": LOGO_THEME.stitchBlue,
  "--gold": LOGO_THEME.stitchBlue,
  "--gold-bronze": LOGO_THEME.stitchBlue,
  "--gold-deep": LOGO_THEME.stitchBlueHover,
  "--gold-soft": `rgba(${colors.primaryRgb}, 0.12)`,
  "--primary": LOGO_THEME.stitchBlue,
  "--primary-hover": LOGO_THEME.stitchBlueHover,
  "--primary-rgb": LOGO_THEME.primaryRgb,
  "--teal-rgb": LOGO_THEME.tealRgb,
  "--navy-rgb": LOGO_THEME.navyRgb,
  "--white-rgb": LOGO_THEME.whiteRgb,
  "--accent": LOGO_THEME.stitchBlue,
  "--border": STITCH_LIGHT_PALETTE.border,
  "--border-subtle": STITCH_LIGHT_PALETTE.borderSubtle,
  "--circuit-opacity": String(LOGO_THEME.circuitOpacity),
  "--navy-900": LOGO_THEME.ink,
  "--navy-800": LOGO_THEME.stitchBlue,
  "--navy-mist": LOGO_THEME.surfaceSoft,
  "--navy-soft": `rgba(${colors.primaryRgb}, 0.08)`,
  "--navy-border": STITCH_LIGHT_PALETTE.border,
  "--focus-ring": `rgba(${colors.primaryRgb}, 0.45)`,
  "--gold-soft-wash": `rgba(${colors.primaryRgb}, 0.08)`,
  "--font-display": typography.fontFamily,
  "--font-body": typography.fontFamily,
  "--display-weight": String(typography.displayWeight),
  "--tracking-tighter": typography.displayTracking,
  "--label-tracking": typography.labelTracking,
  "--stack-lg": spacing.stackLg,
  "--radius-card": radius.card,
  "--home-core-pillars-surface": colors.surfaceContainerLow,
} as const;

export type LogoCssVariableName = keyof typeof LOGO_CSS_VARIABLES;
